### ISSUE TITLE
implement thru 38:22 = confirm animationState in console

### ISSUE THREAD

**Issue by andysmith26** [FinnKinsellaFarrell/Sprite-Animation#1]
https://www.youtube.com/watch?v=CY0HE277IBM

**Comment by andysmith26** [comment]
please fix bug at bottom of the file and implement animation states

**Comment by FinnKinsellaFarrell** [comment]
39: 30

**Comment by andysmith26** [comment]
that timestamp doesn't look right for this task ---- oops! --- please start next class by writing a comment here with your next task (as if you had written it last class 😄 )

**Comment by FinnKinsellaFarrell** [comment]
Sorry for the issue. My next task is to go from 25:21 to  completion (40:00).

**Comment by FinnKinsellaFarrell** [comment]
ended on 38:19, fixed infinite loop, next task is to run things in the developer console.

**Comment by FinnKinsellaFarrell** [comment]
Trouble shot key capitalization.
